//NOTE: Generated by AI. May have strange errors. Use with caution!

using UnityEngine;
using UnityEditor;
using System.IO;

public class MapScreenshotTool : EditorWindow
{
    private Camera screenshotCamera;
    private string outputPath = "Assets/Sprites/Map/Level Maps/New/";
    private string fileName = "Basement";
    private int imageWidth = 1024;
    private int imageHeight = 1024;
    private bool removeBackground = true;
    private Color backgroundColor = Color.clear;
    private bool autoCleanupCamera = true;
    
    [MenuItem("Tools/Map Screenshot Tool")]
    public static void ShowWindow()
    {
        GetWindow<MapScreenshotTool>("Map Screenshot Tool");
    }
    
    void OnGUI()
    {
        GUILayout.Label("Map Screenshot Generator", EditorStyles.boldLabel);
        
        screenshotCamera = (Camera)EditorGUILayout.ObjectField("Screenshot Camera", screenshotCamera, typeof(Camera), true);
        
        // Show camera info if camera is assigned
        if (screenshotCamera != null)
        {
            EditorGUILayout.Space();
            EditorGUILayout.LabelField("Camera Settings", EditorStyles.boldLabel);
            
            float currentSize = screenshotCamera.orthographicSize;
            float newSize = EditorGUILayout.FloatField("Orthographic Size", currentSize);
            if (newSize != currentSize)
            {
                screenshotCamera.orthographicSize = newSize;
            }
            
            Vector3 currentPos = screenshotCamera.transform.position;
            Vector3 newPos = EditorGUILayout.Vector3Field("Position", currentPos);
            if (newPos != currentPos)
            {
                screenshotCamera.transform.position = newPos;
            }
            
            EditorGUILayout.HelpBox($"Current Orthographic Size: {screenshotCamera.orthographicSize:F2}\nTry values between 10-50 for better detail", MessageType.Info);
        }
        
        GUILayout.Space(10);
        
        fileName = EditorGUILayout.TextField("File Name", fileName);
        outputPath = EditorGUILayout.TextField("Output Path", outputPath);
        
        GUILayout.Space(10);
        
        imageWidth = EditorGUILayout.IntField("Image Width", imageWidth);
        imageHeight = EditorGUILayout.IntField("Image Height", imageHeight);
        
        GUILayout.Space(10);
        
        removeBackground = EditorGUILayout.Toggle("Transparent Background", removeBackground);
        if (!removeBackground)
        {
            backgroundColor = EditorGUILayout.ColorField("Background Color", backgroundColor);
        }
        
        autoCleanupCamera = EditorGUILayout.Toggle("Auto-cleanup Camera", autoCleanupCamera);
        
        GUILayout.Space(20);
        
        if (GUILayout.Button("Take Screenshot"))
        {
            TakeScreenshot();
        }
        
        GUILayout.Space(10);
        
        if (GUILayout.Button("Setup Camera for Basement"))
        {
            SetupCameraForBasement();
        }
        
        if (screenshotCamera != null)
        {
            GUILayout.Space(5);
            if (GUILayout.Button("Focus Camera on Basement"))
            {
                FocusCameraOnBasement();
            }
        }
        
        GUILayout.Space(10);
        
        // Cleanup section
        EditorGUILayout.LabelField("Cleanup", EditorStyles.boldLabel);
        if (GUILayout.Button("Remove All Screenshot Cameras"))
        {
            CleanupAllScreenshotCameras();
        }
        
        GUILayout.Space(10);
        
        EditorGUILayout.HelpBox("Instructions:\n1. Load a scene with the basement prefab\n2. Click 'Setup Camera for Basement' to auto-create and position a camera\n3. Use 'Focus Camera on Basement' to recalculate bounds\n4. Manually adjust 'Orthographic Size' (try 10-50 for better detail)\n5. Click 'Take Screenshot'", MessageType.Info);
    }
    
    void SetupCameraForBasement()
    {
        // Try to find the basement prefab in the scene
        GameObject basementPrefab = GameObject.Find("basement");
        if (basementPrefab == null)
        {
            // Try to instantiate it if it's not in the scene
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>("Assets/Third Party Assets/Tiled2Unity/Prefabs/basement.prefab");
            if (prefab != null)
            {
                basementPrefab = PrefabUtility.InstantiatePrefab(prefab) as GameObject;
                EditorUtility.DisplayDialog("Info", "Basement prefab instantiated in scene.", "OK");
            }
            else
            {
                EditorUtility.DisplayDialog("Error", "Could not find basement prefab. Please ensure it exists in the scene or at the expected path.", "OK");
                return;
            }
        }
        
        // Create a new camera for screenshots
        GameObject cameraObj = new GameObject("Map Screenshot Camera");
        screenshotCamera = cameraObj.AddComponent<Camera>();
        
        // Configure camera settings
        screenshotCamera.orthographic = true;
        screenshotCamera.clearFlags = removeBackground ? CameraClearFlags.SolidColor : CameraClearFlags.SolidColor;
        screenshotCamera.backgroundColor = removeBackground ? Color.clear : backgroundColor;
        screenshotCamera.cullingMask = -1; // Render everything
        
        // Position camera above the basement
        Bounds bounds = GetBounds(basementPrefab);
        Vector3 center = bounds.center;
        screenshotCamera.transform.position = new Vector3(center.x, center.y, center.z - 10f);
        screenshotCamera.transform.rotation = Quaternion.identity;
        
        // Calculate a much tighter orthographic size for better detail
        // Use a smaller multiplier to zoom in more on the actual content
        float maxSize = Mathf.Max(bounds.size.x, bounds.size.y) * 0.52f; // Reduced from 0.6f
        screenshotCamera.orthographicSize = maxSize;
        
        Debug.Log($"Basement bounds: {bounds}");
        Debug.Log($"Camera orthographic size set to: {maxSize}");
        Debug.Log($"Camera position: {screenshotCamera.transform.position}");
        
        EditorUtility.DisplayDialog("Success", $"Camera setup complete!\nBounds: {bounds.size}\nOrthographic Size: {maxSize:F2}\n\nYou can manually adjust the orthographic size in the inspector for better framing.", "OK");
    }
    
    void FocusCameraOnBasement()
    {
        if (screenshotCamera == null)
        {
            EditorUtility.DisplayDialog("Error", "No camera assigned.", "OK");
            return;
        }
        
        GameObject basementPrefab = GameObject.Find("basement");
        if (basementPrefab == null)
        {
            EditorUtility.DisplayDialog("Error", "Could not find basement in scene.", "OK");
            return;
        }
        
        Bounds bounds = GetTightBounds(basementPrefab);
        Vector3 center = bounds.center;
        screenshotCamera.transform.position = new Vector3(center.x, center.y, center.z - 10f);
        
        // Use a much smaller multiplier for better detail
        float maxSize = Mathf.Max(bounds.size.x, bounds.size.y) * 0.52f;
        screenshotCamera.orthographicSize = maxSize;
        
        Debug.Log($"Focused on basement - Bounds: {bounds}, Orthographic Size: {maxSize:F2}");
        EditorUtility.DisplayDialog("Success", $"Camera focused on basement!\nOrthographic Size: {maxSize:F2}\nBounds: {bounds.size}", "OK");
    }
    
    Bounds GetBounds(GameObject obj)
    {
        Bounds bounds = new Bounds(obj.transform.position, Vector3.zero);
        Renderer[] renderers = obj.GetComponentsInChildren<Renderer>();
        
        foreach (Renderer renderer in renderers)
        {
            bounds.Encapsulate(renderer.bounds);
        }
        
        return bounds;
    }
    
    Bounds GetTightBounds(GameObject obj)
    {
        Renderer[] renderers = obj.GetComponentsInChildren<Renderer>();
        
        if (renderers.Length == 0)
        {
            return new Bounds(obj.transform.position, Vector3.one);
        }
        
        Bounds bounds = renderers[0].bounds;
        
        // Only include renderers that actually have visible content
        foreach (Renderer renderer in renderers)
        {
            // Skip if renderer is disabled or has no material
            if (!renderer.enabled || renderer.material == null)
                continue;
                
            // Skip very small objects that might be artifacts
            if (renderer.bounds.size.magnitude < 0.1f)
                continue;
                
            bounds.Encapsulate(renderer.bounds);
        }
        
        Debug.Log($"Calculated tight bounds: {bounds} from {renderers.Length} renderers");
        return bounds;
    }
    
    void CleanupAllScreenshotCameras()
    {
        // Find all GameObjects with "Screenshot Camera" in the name
        GameObject[] allObjects = FindObjectsOfType<GameObject>();
        int cleanedUp = 0;
        
        foreach (GameObject obj in allObjects)
        {
            if (obj.name.Contains("Map Screenshot Camera") || obj.name.Contains("Screenshot Camera"))
            {
                // Clear reference if this is our current camera
                if (screenshotCamera != null && screenshotCamera.gameObject == obj)
                {
                    screenshotCamera = null;
                }
                
                DestroyImmediate(obj);
                cleanedUp++;
            }
        }
        
        if (cleanedUp > 0)
        {
            EditorUtility.DisplayDialog("Cleanup Complete", $"Removed {cleanedUp} screenshot camera(s) from the scene.", "OK");
        }
        else
        {
            EditorUtility.DisplayDialog("Cleanup Complete", "No screenshot cameras found to remove.", "OK");
        }
    }
    
    void TakeScreenshot()
    {
        if (screenshotCamera == null)
        {
            EditorUtility.DisplayDialog("Error", "Please assign a camera for taking the screenshot.", "OK");
            return;
        }
        
        // Ensure output directory exists
        if (!Directory.Exists(outputPath))
        {
            Directory.CreateDirectory(outputPath);
        }
        
        // Store original camera settings
        RenderTexture originalTarget = screenshotCamera.targetTexture;
        CameraClearFlags originalClearFlags = screenshotCamera.clearFlags;
        Color originalBackgroundColor = screenshotCamera.backgroundColor;
        
        // Configure camera for screenshot
        if (removeBackground)
        {
            screenshotCamera.clearFlags = CameraClearFlags.SolidColor;
            screenshotCamera.backgroundColor = Color.clear;
        }
        
        // Create render texture
        RenderTexture renderTexture = new RenderTexture(imageWidth, imageHeight, 24, RenderTextureFormat.ARGB32);
        screenshotCamera.targetTexture = renderTexture;
        
        // Render the camera
        screenshotCamera.Render();
        
        // Read pixels from render texture
        RenderTexture.active = renderTexture;
        Texture2D screenshot = new Texture2D(imageWidth, imageHeight, TextureFormat.ARGB32, false);
        screenshot.ReadPixels(new Rect(0, 0, imageWidth, imageHeight), 0, 0);
        screenshot.Apply();
        
        // Save to file
        byte[] data = screenshot.EncodeToPNG();
        string fullPath = Path.Combine(outputPath, fileName + ".png");
        File.WriteAllBytes(fullPath, data);
        
        // Cleanup
        RenderTexture.active = null;
        screenshotCamera.targetTexture = originalTarget;
        screenshotCamera.clearFlags = originalClearFlags;
        screenshotCamera.backgroundColor = originalBackgroundColor;
        DestroyImmediate(renderTexture);
        DestroyImmediate(screenshot);
        
        // Refresh asset database and configure import settings
        AssetDatabase.Refresh();
        
        // Configure the imported texture settings to match existing map files
        TextureImporter importer = AssetImporter.GetAtPath(fullPath) as TextureImporter;
        if (importer != null)
        {
            importer.textureType = TextureImporterType.Sprite;
            importer.spriteImportMode = SpriteImportMode.Single;
            importer.filterMode = FilterMode.Point;
            importer.textureCompression = TextureImporterCompression.Uncompressed;
            AssetDatabase.ImportAsset(fullPath);
        }
        
        // Auto-cleanup camera if enabled
        if (autoCleanupCamera && screenshotCamera != null)
        {
            GameObject cameraObj = screenshotCamera.gameObject;
            screenshotCamera = null; // Clear reference first
            DestroyImmediate(cameraObj);
        }
        
        EditorUtility.DisplayDialog("Success", $"Screenshot saved to: {fullPath}" + (autoCleanupCamera ? "\nCamera automatically cleaned up." : ""), "OK");
    }
}
