//NOTE: Generated by AI. May have strange errors. Use with caution!

using UnityEngine;
using UnityEditor;

public class WebGLBuildFix
{
    [MenuItem("Build/Fix WebGL Audio Settings")]
    public static void FixWebGLAudioSettings()
    {
        // Set WebGL-specific player settings to avoid FMOD issues
        PlayerSettings.WebGL.compressionFormat = WebGLCompressionFormat.Gzip;
        PlayerSettings.WebGL.nameFilesAsHashes = true;
        PlayerSettings.WebGL.dataCaching = true;
        PlayerSettings.WebGL.debugSymbolMode = WebGLDebugSymbolMode.Off;
        
        // Critical: Set stripping level to minimal to avoid audio issues
        PlayerSettings.SetManagedStrippingLevel(BuildTargetGroup.WebGL, ManagedStrippingLevel.Minimal);
        
        // Set API compatibility level
        PlayerSettings.SetApiCompatibilityLevel(BuildTargetGroup.WebGL, ApiCompatibilityLevel.NET_Standard_2_0);
        
        // Add WebGL linker flags to handle undefined FMOD symbols
        string currentArgs = PlayerSettings.WebGL.emscriptenArgs;
        if (!currentArgs.Contains("ERROR_ON_UNDEFINED_SYMBOLS=0"))
        {
            PlayerSettings.WebGL.emscriptenArgs = currentArgs + " -s ERROR_ON_UNDEFINED_SYMBOLS=0";
        }
        
        Debug.Log("WebGL audio settings configured:");
        Debug.Log("- Stripping level: Minimal");
        Debug.Log("- Added ERROR_ON_UNDEFINED_SYMBOLS=0 to handle FMOD issues");
        Debug.Log("- Compression: Gzip");
        Debug.Log("Try building again - FMOD errors should be resolved.");
    }
    
    public static void BuildWebGLWithFix()
    {
        // Apply the fix first
        FixWebGLAudioSettings();
        
        // Get all scenes in build settings
        string[] scenes = new string[EditorBuildSettings.scenes.Length];
        for (int i = 0; i < scenes.Length; i++)
        {
            scenes[i] = EditorBuildSettings.scenes[i].path;
        }
        
        string buildPath = "../WebGL_Build_Fixed";
        
        Debug.Log("Building WebGL with audio fixes to: " + buildPath);
        
        // Configure WebGL build options
        BuildPlayerOptions buildPlayerOptions = new BuildPlayerOptions();
        buildPlayerOptions.scenes = scenes;
        buildPlayerOptions.locationPathName = buildPath;
        buildPlayerOptions.target = BuildTarget.WebGL;
        buildPlayerOptions.options = BuildOptions.None;
        
        // Perform the build
        var report = BuildPipeline.BuildPlayer(buildPlayerOptions);
        
        if (report.summary.result == UnityEditor.Build.Reporting.BuildResult.Succeeded)
        {
            Debug.Log("Build succeeded: " + report.summary.totalSize + " bytes");
        }
        else
        {
            Debug.LogError("Build failed with " + report.summary.totalErrors + " errors");
        }
    }
}
